version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:24.14
    resource_class: medium
    working_directory: ~/project
    environment:
      BASE_URL: https://restful-booker.herokuapp.com

    steps:
      - checkout

      - run:
          name: Instalar dependências
          command: npm ci

      - run:
          name: Instalar browsers do Playwright
          command: npx playwright install --with-deps

      - run:
          name: Rodar testes
          command: npm run api

      - store_artifacts:
          path: playwright-report
          destination: playwright-report

      - store_test_results:
          path: test-results

workflows:
  version: 2
  pipeline:
    jobs:
      - test